--OT

SELECT * FROM EMP;

--SELECT DEPTNO, COUNT(DEPTNO), TRUNC(AVG(SAL),3), SUM(SAL), MIN(SAL), MAX(SAL)
SELECT DEPTNO, COUNT(DEPTNO), AVG(SAL), SUM(SAL), MIN(SAL), MAX(SAL)
FROM EMP
GROUP BY DEPTNO;

-- 1
SELECT EMPNO, ENAME, SAL
FROM EMP;

-- 2
SELECT EMPNO AS "사원번호", ENAME AS "사원명", SAL AS "월급", SAL*12 AS "연봉"
FROM EMP;

-- 3
SELECT FIRST_NAME ||' ' ||LAST_NAME AS "이름", SALARY, SALARY +300
FROM EMPLOYEES;

-- 4
SELECT FIRST_NAME || ' ' ||  LAST_NAME AS "성 이름",RPAD(LAST_NAME, 8, ' ')  ||' 1 Year salary = ' || TO_CHAR(SALARY*12, '999,999') || ' 달러' AS "연봉"
FROM EMPLOYEES;

-- 5
SELECT EMPLOYEE_ID AS "사원 번호" ,FIRST_NAME|| ' ' ||LAST_NAME AS "성명", TO_CHAR(HIRE_DATE, 'YYYY-MM-DD') AS "입사일"
FROM EMPLOYEES;
--WHERE EXTRACT(HIRE_DATE >= TO_DATE('1995-01-01', 'YYYY-MM-DD'));
