-- 제약조건
-- 1. NOT NULL
-- 2. UNIQUE
-- 3. PRIMARY KEY
-- 4. FOREIGN KEY
-- 5. CHECH
-- 6. DEFAULT

CREATE TABLE SAMPLE(
	NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(20),
	AGE NUMBER
);

INSERT ALL
	INTO SAMPLE VALUES(1, '양지은',10)
	INTO SAMPLE VALUES(2, '박우진',10)
	INTO SAMPLE VALUES(3, '김태온',10)
SELECT * FROM DUAL;

-- 10, 11만 AGE의 값으로 올 수 있다.
-- CHECK(AGE IN(10,11)) <-- 제약조건 속성
ALTER TABLE SAMPLE MODIFY AGE NUMBER CHECK(AGE IN(10,11));

-- SQL Error [2290] [23000]: ORA-02290: check constraint (TEST.SYS_C007221) violated
-- 제약조건에 걸림
INSERT INTO SAMPLE VALUES(4, '정지우',12);

SELECT * FROM SAMPLE;

