TRUNCATE 

DROP TABLE EMP;

CREATE TABLE EMP(
	NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(20),
	AGE NUMBER
);

SELECT * FROM EMP;

DROP INDEX SYS_CO007223;

--
--
--

INSERT ALL
	INTO EMP VALUES(1, '둘리',10)
	INTO EMP VALUES(2, '또치',10)
	INTO EMP VALUES(3, '고길동',10)
SELECT * FROM DUAL;

-- NAME 컬럼에 INDEX 추가
CREATE INDEX EMP_IDX01 ON EMP(NAME);
SELECT * FROM EMP WHERE NAME='둘리';
SELECT * FROM EMP ORDER BY NAME;
SELECT * FROM EMP ORDER BY NO;

-- NO 컬럼과 NAME 컬럼에 인덱스 추가
-- 넘버를 기준으로 정렬한 후 네임기준으로 정렬
CREATE INDEX EMP_IDX01 ON EMP(NO, NAME);
SELECT * FROM EMP WHERE NO=1;
SELECT * FROM EMP WHERE NO=1 AND NAME='둘리';
SELECT * FROM EMP WHERE NAME='둘리'; --인덱스 적용 X, 넘버가 먼저 와야함

SELECT * FROM EMP WHERE NO=1 OR NAME='또치';


-- 컬럼에 중복된 값이 있으면 유니크인덱스가 사용되지않음...
-- index 기능 + unique를 통해 데이터가 중복 되지 않게함 (무결성 보장)
-- 중복방지, 검색속도 향상
CREATE UNIQUE INDEX EMP_UK3 ON EMP(AGE);
CREATE UNIQUE INDEX EMP_UK2 ON EMP(NAME);
CREATE UNIQUE INDEX EMP_UK ON EMP(NO);



DROP INDEX EMP_UK;
DROP INDEX EMP_UK2;
DROP INDEX EMP_IDX01;

drop table emp;

CREATE TABLE EMP (

NO NUMBER primary key,

NAME VARCHAR2(20) not null,

AGE NUMBER

);

INSERT INTO EMP (NO, NAME, AGE) VALUES (1, '둘리', 10);

INSERT INTO EMP (NO, NAME, AGE) VALUES (2, '또치', 10);