-- 데이터사전

SELECT * FROM DBA_TABLES; -- 1719개
SELECT * FROM DBA_INDEXES; -- 3279개
SELECT * FROM DBA_VIEWS; -- 4090개

-- ALL 자기 자신 계정 + 다른 계졍들
SELECT * FROM ALL_TABLES; -- 1719개
SELECT * FROM ALL_INDEXES; -- 2717개
SELECT * FROM ALL_VIEWS; -- 4090개

-- USER 자기 자신 계정
SELECT * FROM USER_TABLES; -- 20개
SELECT * FROM USER_INDEXES; -- 33개
SELECT * FROM USER_VIEWS; -- 1개