-- HAVING
-- GROUP BY절을 사용할 때 WHERE 절처럼 사용하는 조건절
-- 데이터를 그룹핑 한 후 특징들을 골라낼 때 사용한다.

-- <SELECT 문의 논리적 수행 순서> 꼭 순서를 지켜야함
--
-- SELECT         –1
-- FROM            –2
-- WHERE          –3
-- GROUP BY    –4
-- HAVING         –5
-- ORDER BY    –6

	-- HAVING 사용하기
SELECT TYPE, COUNT(NAME) AS COUNT 
FROM GIFT 
GROUP BY TYPE 
HAVING COUNT(NAME)>=2
ORDER BY TYPE;
--HAVING, ORDER BY, GROUP BY 에는 
--SELECT된 내용만 사용 가능

SELECT * FROM GIFT;
SELECT TYPE, COUNT(NAME) AS COUNT 
FROM GIFT 
GROUP BY TYPE 
HAVING COUNT(NAME)>=1
ORDER BY TYPE;

-- 에러
SELECT * FROM GIFT;
SELECT TYPE, TRUNC(PRICE,-2) AS TRUNC
FROM GIFT 
GROUP BY TYPE
HAVING TRUNC(PRICE,-2)>=0
ORDER BY TYPE;

-- 정상// HAVING에 TRUNC를 추가해야함
SELECT TYPE, TRUNC(PRICE, -2) AS TRUNC
FROM GIFT
GROUP BY TYPE, TRUNC(PRICE, -2)
HAVING TRUNC(PRICE, -2) >= 200000
ORDER BY TYPE;

--
--
SELECT ABS(2) FROM DUAL;
SELECT SIGN(-5) FROM DUAL;
SELECT SIGN(5) FROM DUAL;
SELECT SIGN(0) FROM DUAL;
SELECT ROUND(163.76, 1) FROM DUAL;
SELECT ROUND(163.76, -2) FROM DUAL;
SELECT TRUNC(54.29, 1) FROM DUAL;
SELECT TRUNC(54.29, -2) FROM DUAL;
SELECT CEIL(72.86) FROM DUAL;
SELECT CEIL(-33.4) FROM DUAL;
SELECT FLOOR(22.3) FROM DUAL;
SELECT FLOOR(-22.3) FROM DUAL;
SELECT MOD(15, 7) FROM DUAL;
SELECT MOD(15, -4) FROM DUAL;