-- 윈도우 함수

-- 성적 테이블 작성
CREATE TABLE STUDENT_GRADE
(
	STUDENT_ID NUMBER PRIMARY KEY,
	STUDENT_NAME VARCHAR2(20) NOT NULL,
	SCORE NUMBER NOT NULL
);

-- 힉생 성적 데이터 입력
INSERT INTO STUDENT_GRADE (STUDENT_ID, STUDENT_NAME, SCORE) VALUES (1, '이름 1', 391);
INSERT INTO STUDENT_GRADE (STUDENT_ID, STUDENT_NAME, SCORE) VALUES (2, '이름 2', 489);
INSERT INTO STUDENT_GRADE (STUDENT_ID, STUDENT_NAME, SCORE) VALUES (3, '이름 3', 437);
INSERT INTO STUDENT_GRADE (STUDENT_ID, STUDENT_NAME, SCORE) VALUES (4, '이름 4', 339);
INSERT INTO STUDENT_GRADE (STUDENT_ID, STUDENT_NAME, SCORE) VALUES (5, '이름 5', 493);
INSERT INTO STUDENT_GRADE (STUDENT_ID, STUDENT_NAME, SCORE) VALUES (6, '이름 6', 361);
INSERT INTO STUDENT_GRADE (STUDENT_ID, STUDENT_NAME, SCORE) VALUES (7, '이름 7', 470);
INSERT INTO STUDENT_GRADE (STUDENT_ID, STUDENT_NAME, SCORE) VALUES (8, '이름 8', 456);
INSERT INTO STUDENT_GRADE (STUDENT_ID, STUDENT_NAME, SCORE) VALUES (9, '이름 9', 417);
INSERT INTO STUDENT_GRADE (STUDENT_ID, STUDENT_NAME, SCORE) VALUES (10, '이름 10', 391);
INSERT INTO STUDENT_GRADE (STUDENT_ID, STUDENT_NAME, SCORE) VALUES (11, '이름 11', 461);
INSERT INTO STUDENT_GRADE (STUDENT_ID, STUDENT_NAME, SCORE) VALUES (12, '이름 12', 298);
INSERT INTO STUDENT_GRADE (STUDENT_ID, STUDENT_NAME, SCORE) VALUES (13, '이름 13', 443);
INSERT INTO STUDENT_GRADE (STUDENT_ID, STUDENT_NAME, SCORE) VALUES (14, '이름 14', 426);
INSERT INTO STUDENT_GRADE (STUDENT_ID, STUDENT_NAME, SCORE) VALUES (15, '이름 15', 383);

-- 순위 함수
SELECT STUDENT_NAME, SCORE, RANK() OVER(ORDER BY SCORE DESC) FROM STUDENT_GRADE;
SELECT STUDENT_NAME, SCORE, DENSE_RANK() OVER(ORDER BY SCORE DESC) FROM STUDENT_GRADE;
SELECT STUDENT_NAME, SCORE, ROW_NUMBER() OVER(ORDER BY SCORE DESC) FROM STUDENT_GRADE;

-- 집계 함수
SELECT TYPE, SUM(price) AS SUM FROM GIFT GROUP BY TYPE;
SELECT TYPE, PRICE, SUM(PRICE) OVER(PARTITION BY TYPE) AS P FROM GIFT;
SELECT TYPE, MIN(price) AS MIN FROM GIFT GROUP BY TYPE;
SELECT TYPE, AVG(price) AS AVG FROM GIFT GROUP BY TYPE;
SELECT TYPE, COUNT(NAME) AS COUNT FROM GIFT GROUP BY TYPE;