SELECT ROUND(163.76, 1) FROM DUAL;
SELECT ROUND(163.76, -2) FROM DUAL;

SELECT TRUNC(54.29, 1) FROM DUAL;
SELECT TRUNC(54.29, -1) FROM DUAL;

SELECT CEIL(72.86) FROM DUAL;
SELECT CEIL(-33.4) FROM DUAL;


SELECT ID, DECODE(ID, 1, 'BLUE', 2, 'RED', 3, 'YELLOW', 4, 'BLACK', 5, 'WHITE') FROM CUSTOMER;

SELECT ID
     , CASE WHEN ID = 1 THEN 'BLUE'
            WHEN ID = 2 THEN 'RED'
            WHEN ID = 3 THEN 'YELLOW'
            WHEN ID = 4 THEN 'BLACK'
            ELSE 'WHITE'
       END AS TEST
  FROM CUSTOMER;
