SELECT * FROM CUSTOMER;
SELECT * FROM CONTACTS;
SELECT * FROM GIFT;
SELECT * FROM ORDERS;

-- 순서대로 정렬해서 조회 ... 오름차순 정렬
SELECT * FROM CUSTOMER ORDER BY id ASC; 
SELECT * FROM CUSTOMER ORDER BY ADDRESS ASC;	

-- 역정렬해서 조회 ... 내림차순 정렬
SELECT * FROM CUSTOMER ORDER BY id DESC;
SELECT * FROM CUSTOMER ORDER BY ADDRESS DESC;

SELECT 'SQL' || '개발자' FROM DUAL;


SELECT '이름:' || NAME || '입니다.' AS INTRO FROM CUSTOMER;

SELECT * FROM CUSTOMER ;

SELECT * FROM CUSTOMER 
WHERE ID BETWEEN 2 AND 4; 


-- 비교연산자
-- = : 같다
SELECT * FROM CUSTOMER
WHERE ID=1;

-- 논리연산자 AND, OR, NOT
SELECT * FROM CUSTOMER 
WHERE NAME='둘리' AND ADDRESS='서울';

SELECT * FROM CUSTOMER 
WHERE  ADDRESS='인천' OR ADDRESS='서울';

SELECT * FROM CUSTOMER 
WHERE NOT ADDRESS='서울' ;

SELECT * FROM ORDERS;

-- 산술연산자(NUMBER, DATE TYPE에서 사용)
-- (), +, /, +, -
-- 
SELECT ORDER_ID + (SALESMAN_ID * ORDER_ID) FROM ORDERS;

SELECT ORDER_ID * SALESMAN_ID AS HAP FROM ORDERS;
SELECT ORDER_ID * SALESMAN_ID FROM ORDERS;

SELECT ORDER_ID / SALESMAN_ID AS NA FROM ORDERS;

SELECT ORDER_ID + SALESMAN_ID AS PLUS FROM ORDERS;

SELECT ORDER_ID - SALESMAN_ID AS MIN FROM ORDERS;


